# Generated by Django 3.2.5 on 2021-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите заголовок для новости', max_length=150)),
                ('content', models.TextField(help_text='введите содержание')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, help_text='добавьте фотографию(если требуется)', upload_to='photo/%Y/%m/%d')),
                ('file', models.FileField(blank=True, help_text='добавьте файл(если требуется)', upload_to='file/%Y/%m/%d')),
                ('published', models.BooleanField(default=True, help_text='публиковать новость?')),
            ],
        ),
    ]
