# Generated by Django 3.2.5 on 2021-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(help_text='эл.почта', max_length=254, unique=True),
        ),
    ]
