# Generated by Django 3.2.5 on 2021-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title_category',
            field=models.CharField(help_text='Введите название категории', max_length=100, unique=True),
        ),
    ]
