# Generated by Django 3.2 on 2021-04-28 17:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFlatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Основной текстовый контент страницы')),
                ('text_block', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='дополнительный блок текста')),
                ('flatpage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'Содержание страницы',
                'verbose_name_plural': 'Содержание страницы',
            },
        ),
    ]
